
#+TITLE: Physics Notes
#+OPTIONS: toc:nil
#+OPTIONS: H:12

#+latex_class_options: [12pt]
#+latex_header: \usepackage{titlesec}
#+latex_header: \setcounter{secnumdepth}{12}
#+latex_header: \titleformat{\paragraph}
#+latex_header: {\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
#+latex_header: \titlespacing*{\paragraph}
#+latex_header: {0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
#+latex_header: \usepackage{indentfirst}
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage[export]{adjustbox}
#+latex_header: \usepackage{tikz-feynman}
#+latex_header: \usepackage[left=2cm, right=2cm, top=2cm, bottom=2cm]{geometry}
#+latex_header: \usepackage{tikz}
#+latex_header: \usetikzlibrary{arrows.meta, decorations.pathreplacing, decorations.markings}
#+latex_header: \raggedbottom
#+latex_header: \usepackage{float}
#+latex_header: \clearpage
#+latex_header: \usepackage{longtable}
#+latex_header: \usepackage{array}
#+latex_header: \usepackage{multirow}
#+latex_header: \newcolumntype{C}[1]{>{\centering\arraybackslash}p{#1}}
#+latex_header: \usepackage{fancyhdr}
#+latex_header: \pagestyle{fancy}
#+latex_header: \fancyhf{}
#+latex_header: \rhead{\emph{Alexander}}
#+latex_header: \lhead{Physics}
#+latex_header: \rfoot{\thepage}
#+latex_header: \lfoot{\leftmark}
#+latex_header: \renewcommand{\headrulewidth}{1pt}
#+latex_header: \renewcommand{\footrulewidth}{1pt}
#+latex_header: \setlength{\parindent}{0pt}

#+begin_export latex
\thispagestyle{empty}
\begin{figure}[H]
\centering
% \includegraphics[width=0.8\textwidth,keepaspectratio,frame]{./images/}
\end{figure}
\newpage
\tableofcontents
\newpage
#+end_export

* Particle Physics
** Atoms & Nuclei

An atom is composed of a positively charged, centrally located mass called the /nucleus/, surrounded by negatively charged /electrons/. These electrons are held in the atom by the /electrostatic force of attraction/ from the positive nucleus. The ratio of electron mass to nucleon mass is about $0.0005$. Therefore the majority of an atoms mass is contained in the nucleus. The ratio of the diameter of a nucleus to the typical diameter of an atom is about $0.000001$.

#+begin_export latex

% insert table about p, n and e

#+end_export

*** Isotopes

Every atom of a particular element has the same number of protons as the next. The proton number, also called the atomic number and denoted with the letter $Z$, identifies particular atoms. Atoms of a certain element can have *different* neutron totals. These atoms share the same proton number so they are of the same element and are /isotopes/ of that element. The total number of nucleons (neutrons and protons) is denoted with the letter $A$ and sometimes called the mass number. The number of neutrons in a nucleus is equal to $A - Z$. An unspecified element may be represented with the notation $^{A}_{Z}X$ where the mass number is displayed above the proton number. Each type of a nucleus of element $X$ is called a /nuclide/.

*** Specific Charge

The specific charge of a charged particle is the total charge over its mass. The specific charge for a nucleus, nucleon, electron, ion or other particle can all be calculated.

*** Strong Nuclear Force

Protons in a nucleus experience repulsion from one another due to their like charge. A separate force is required to oppose the electrostatic force between protons and prevent the disintegration of nuclei. This force is known as the /Strong Nuclear Force/.

- The range of the strong force is limited to about $3-4fm$, the typical diameter of an a small nucleus. The range of the electrostatic force is unlimited, but decreases with distance.

- The effect felt between a neutron and a proton is the same as the force experienced between any nucleon combination.

- The strong force is repulsive below $0.5fm$ and attractive from this point to the extent of its range. This prevents nucleons being pushed into each other and hence the collapse of a nucleus.

#+begin_export latex

% graph of force against seperation

#+end_export

*** Force Carriers

Forces acting on objects cause a change in momentum according to $F = mv/t$. This is observed when two charged particles approach one another. For example, the electromagnetic force between particles is due to an exchange particle, in this case a /virtual photon/.

#+begin_export latex

\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {};
    \vertex[right=.3 of i1] (i3) {\(p\)};
    \vertex[above=2 of i1] (f1) {};
    \vertex[right=.3 of f1] (f3) {\(p\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,.2)$) (d);
    \vertex at ($(d) + (.3, 1)$) (f4) {\(p\)};
    \vertex at ($(d) + (.3,-1)$) (f5) {\(p\)};
\diagram*{
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (c) -- [boson, edge label'=\(\gamma \), very thick] (d),
    (d) -- [anti fermion, very thick] (f5),
    (d) -- [fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{Electromagnetic force between two protons}
\end{figure}

#+end_export

*** Weak Interaction

The /Weak Nuclear Force/ causes some nuclear changes, such as beta emission. It is so called as its strength is less than the strong nuclear force, preventing the disintegration of stable nuclei. The exchange particle of the /weak interaction/ is the /W boson/. These are charged particles with a very short range and non-zero rest mass.

** Radioactive Decay

Naturally occurring radioactive isotopes emit three types of radiation:

1. Alpha: $^4_2\alpha$
2. Beta: $^{ \text{ } \text{ } 0}_{-1}\beta^-$ / $^{0}_{1}\beta^+$
3. Gamma: $\gamma$

*** Alpha Emission

An $\alpha$ particle is composed of two neutrons and two protons. The product nucleus $Y$, after $\alpha$ emission has taken place, is a of a different, lighter element.

\[^A_ZX \rightarrow \text{} ^4_2\alpha + \text{} ^{A-4}_{Z-2}Y\]

*** Beta Minus Decay

A $\beta^-$ particle is an electron. During $\beta^-$ emission, a neutron in a neutron-rich nucleus decays into a proton. The underlying change is the conversion of a /down quark/ into an /up quark/. Along with a fast-moving electron, an /electron antineutrino/ is produced.

\[^A_ZX \rightarrow \text{} ^{ \text{ } \text{ }0}_{-1}\beta + \text{} ^{\text{ } \text{ }A}_{Z+1}Y + \bar{\nu}_e\]

#+begin_export latex

\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {\(u\)};
    \vertex[right=.15 of i1] (i2) {\(d\)};
    \vertex[right=.15 of i2] (i3) {\(d\)};
    \vertex[below=.3 of i2] (n) {\(n\)};
    \vertex[above=2 of i1] (f1) {\(u\)};
    \vertex[right=.15 of f1] (f2) {\(d\)};
    \vertex[right=.15 of f2] (f3) {\(u\)};
    \vertex[above=.3 of f2] (p) {\(p\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,.25)$) (d);
    \vertex at ($(d) + (.2, 1)$) (f4) {\(\bar{\nu}_e\)};
    \vertex at ($(d) + (.9,.5)$) (f5) {\(e^-\)};
\diagram*{
    (i1) -- [fermion, opacity=0.5] (a) -- [fermion, opacity=0.5] (f1),
    (i2) -- [fermion, opacity=0.5] (b) -- [fermion, opacity=0.5] (f2),
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (c) -- [boson, edge label'=\(W^-\), momentum, very thick] (d),
    (d) -- [fermion, very thick] (f5),
    (d) -- [anti fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{Beta minus decay}
\end{figure}

#+end_export

*** Beta Plus Decay

A $\beta^+$ particle is a positron. During $\beta^+$ emission, a proton in a proton-rich nucleus decays into a neutron. The underlying change is the conversion of an /up quark/ into an /down quark/. Along with a fast-moving positron, an /electron neutrino/ is produced.

\[^A_ZX \rightarrow \text{} ^{ \text{ } \text{ }0}_{+1}\beta + \text{} ^{\text{ } \text{ }A}_{Z-1}Y + \nu_e\]

#+begin_export latex

\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {\(u\)};
    \vertex[right=.15 of i1] (i2) {\(d\)};
    \vertex[right=.15 of i2] (i3) {\(u\)};
    \vertex[below=.3 of i2] (n) {\(p\)};
    \vertex[above=2 of i1] (f1) {\(u\)};
    \vertex[right=.15 of f1] (f2) {\(d\)};
    \vertex[right=.15 of f2] (f3) {\(d\)};
    \vertex[above=.3 of f2] (p) {\(n\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,.25)$) (d);
    \vertex at ($(d) + (.2, 1)$) (f4) {\(\nu_e\)};
    \vertex at ($(d) + (.9,.5)$) (f5) {\(e^+\)};
\diagram*{
    (i1) -- [fermion, opacity=0.5] (a) -- [fermion, opacity=0.5] (f1),
    (i2) -- [fermion, opacity=0.5] (b) -- [fermion, opacity=0.5] (f2),
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (c) -- [boson, edge label'=\(W^+\), momentum, very thick] (d),
    (d) -- [anti fermion, very thick] (f5),
    (d) -- [fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{Beta plus decay}
\end{figure}

#+end_export

*** Electron Capture

A proton-rich nucleus could also undergo /electron capture/. In this type of decay a proton changes into a neutron after capturing an inner shell electron.

\[^A_ZX + ^{ \text{ } \text{ }0}_{-1}\beta \rightarrow \text{} ^{\text{ } \text{ }A}_{Z-1}Y + \nu_e\]

#+begin_export latex


\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {\(u\)};
    \vertex[right=.15 of i1] (i2) {\(d\)};
    \vertex[right=.15 of i2] (i3) {\(u\)};
    \vertex[below=.3 of i2] (n) {\(p\)};
    \vertex[above=2 of i1] (f1) {\(u\)};
    \vertex[right=.15 of f1] (f2) {\(d\)};
    \vertex[right=.15 of f2] (f3) {\(d\)};
    \vertex[above=.3 of f2] (p) {\(n\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,-.2)$) (d);
    \vertex at ($(d) + (.3, 1)$) (f4) {\(\nu_e\)};
    \vertex at ($(d) + (.3,-1)$) (f5) {\(e^-\)};
\diagram*{
    (i1) -- [fermion, opacity=0.5] (a) -- [fermion, opacity=0.5] (f1),
    (i2) -- [fermion, opacity=0.5] (b) -- [fermion, opacity=0.5] (f2),
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (d) -- [boson, edge label'=\(W^-\), momentum, very thick] (c),
    (d) -- [anti fermion, very thick] (f5),
    (d) -- [fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{Electron capture $W-$ boson}
\end{figure}

#+end_export

The nature of the /W boson/ is not significant/distinguishable. The same diagram could be written:

#+begin_export latex

\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {\(u\)};
    \vertex[right=.15 of i1] (i2) {\(d\)};
    \vertex[right=.15 of i2] (i3) {\(u\)};
    \vertex[below=.3 of i2] (n) {\(p\)};
    \vertex[above=2 of i1] (f1) {\(u\)};
    \vertex[right=.15 of f1] (f2) {\(d\)};
    \vertex[right=.15 of f2] (f3) {\(d\)};
    \vertex[above=.3 of f2] (p) {\(n\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,.2)$) (d);
    \vertex at ($(d) + (.3, 1)$) (f4) {\(\nu_e\)};
    \vertex at ($(d) + (.3,-1)$) (f5) {\(e^-\)};
\diagram*{
    (i1) -- [fermion, opacity=0.5] (a) -- [fermion, opacity=0.5] (f1),
    (i2) -- [fermion, opacity=0.5] (b) -- [fermion, opacity=0.5] (f2),
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (c) -- [boson, edge label'=\(W^+\), momentum, very thick] (d),
    (d) -- [anti fermion, very thick] (f5),
    (d) -- [fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{Electron capture $W+$ boson}
\end{figure}
#+end_export

*** Gamma Emission

Gamma radiation is emitted by an unstable nucleus. This type of emission is pure energy with no mass and no charge. There is no change to the number of nucleons in the nucleus when a $\gamma$ photon is emitted. This type of emission usually happens if the nucleus is in an excited state after one of the previous types of emission.

*** Neutrino Interactions

#+begin_export latex

\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {};
    \vertex[right=.3 of i1] (i3) {\(n\)};
    \vertex[above=2 of i1] (f1) {};
    \vertex[right=.3 of f1] (f3) {\(p\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,.2)$) (d);
    \vertex at ($(d) + (.3, 1)$) (f4) {\(\beta^-\)};
    \vertex at ($(d) + (.3,-1)$) (f5) {\(v\)};
\diagram*{
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (c) -- [boson, edge label'=\(W^- \), very thick] (d),
    (d) -- [anti fermion, very thick] (f5),
    (d) -- [fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{A neutron-neutrino interaction}
\end{figure}

\begin{figure}[H]
\centering
\begin{tikzpicture}[x=30mm, y=30mm]
\begin{feynman}
    \vertex (i1) {};
    \vertex[right=.3 of i1] (i3) {\(p\)};
    \vertex[above=2 of i1] (f1) {};
    \vertex[right=.3 of f1] (f3) {\(n\)};
    \vertex[above=1 of i3] (a);
    \vertex[right=.15 of a] (b);
    \vertex[right=.15 of b] (c);
    \vertex at ($(c) + (1,.2)$) (d);
    \vertex at ($(d) + (.3, 1)$) (f4) {\(\beta^+\)};
    \vertex at ($(d) + (.3,-1)$) (f5) {\(\bar{v}\)};
\diagram*{
    (i3) -- [fermion, very thick] (c) -- [fermion, very thick] (f3),
    (c) -- [boson, edge label'=\(W^+ \), very thick] (d),
    (d) -- [anti fermion, very thick] (f5),
    (d) -- [fermion, very thick] (f4),
};
% \draw[-stealth] (-.4,-.4) -- (-.4,2.2);
% \node at (-.4,2.3) {\(t\)};
\end{feynman}
\end{tikzpicture}
\caption{A proton-antineutrino interaction}
\end{figure}

#+end_export

** Particles & Antiparticles

For each type of particle, there is a corresponding /antiparticle/ which, in a collision event, can release the rest energy of the two particles combined. For any particle, its antiparticle will have the same rest mass and opposite charge if the particle has a charge.

*** Hadrons

Hadrons are /non-fundamental/ particles subject to all basic interactions: strong, weak, gravitational and electromagnetic. All Hadrons are composed of /quarks./ Hadrons can be divided into two categories: /baryons/ and /mesons/.

#+begin_export latex
\begin{figure}[H]
\small
\begin{longtable}{ |C{0.2\textwidth}|C{0.2\textwidth}|C{0.2\textwidth}|C{0.2\textwidth}| }
\hline
&&&\\*
\textbf{Particle} & \textbf{Baryon Number} & \textbf{Strangeness} & \textbf{Charge} \\*
&&&\\*
\hline
\endhead
&&&\\*
$p$&$+1$&$0$&$+1$\\*
&&&\\*
\hline
&&&\\*
$\bar{p}$&$-1$&$0$&$-1$\\*
&&&\\*
\hline
&&&\\*
$n$&$+1$&$0$&$0$\\*
&&&\\*
\hline
&&&\\*
$\bar{n}$&$-1$&$0$&$0$\\*
&&&\\*
\hline
&&&\\*
$\pi ^+$&$0$&$0$&$+1$\\*
&&&\\*
\hline
&&&\\*
$\pi ^0$&$0$&$0$&$0$\\*
&&&\\*
\hline
&&&\\*
$\pi ^-$&$0$&$0$&$-1$\\*
&&&\\*
\hline
&&&\\*
$K^+$&$0$&$+1$&$+1$\\*
&&&\\*
\hline
&&&\\*
$K^0$&$0$&$+1$&$0$\\*
&&&\\*
\hline
&&&\\*
$\bar{K^0}$&$0$&$-1$&$0$\\*
&&&\\*
\hline
&&&\\*
$K^-$&$0$&$-1$&$-1$\\*
&&&\\*
\hline
\end{longtable}
\normalsize
\end{figure}
#+end_export

**** Quarks

#+begin_export latex
\begin{figure}[H]
\small
\begin{longtable}{ |p{0.18\textwidth}|C{0.10\textwidth}|C{0.10\textwidth}|C{0.10\textwidth}|C{0.10\textwidth}|C{0.10\textwidth}|C{0.10\textwidth}| }
\cline{2-7}
\multicolumn{1}{c|}{\multirow{6}{*}{}} & \multicolumn{3}{c|}{} & \multicolumn{3}{c|}{} \\* [-0.9em]
\multicolumn{1}{c|}{} & \multicolumn{3}{c|}{\textbf{Quark}} & \multicolumn{3}{c|}{\textbf{Antiquark}} \\*
\multicolumn{1}{c|}{} & \multicolumn{3}{c|}{} & \multicolumn{3}{c|}{} \\* [-0.9em]
\cline{2-7}
\multicolumn{1}{c|}{}&&&&&& \\* [-0.9em]
\multicolumn{1}{c|}{}& $u$ & $d$ & $s$ & $\bar{u}$ & $\bar{d}$ & $\bar{s}$\\*
\multicolumn{1}{c|}{}&&&&&& \\* [-0.9em]
\hline
\endhead
&&&&&& \\*
charge $Q$ &$+\dfrac{2}{3}$&$-\dfrac{1}{3}$&$-\dfrac{1}{3}$&$-\dfrac{2}{3}$&$+\dfrac{1}{3}$&$+\dfrac{1}{3}$\\*
&&&&&& \\*
\hline
&&&&&& \\*
strangeness $S$ &$0$&$0$&$-1$&$0$&$0$&$+1$\\*
&&&&&& \\*
\hline
&&&&&& \\*
baryon number $B$ &$+\dfrac{1}{3}$&$+\dfrac{1}{3}$&$+\dfrac{1}{3}$&$-\dfrac{1}{3}$&$-\dfrac{1}{3}$&$-\dfrac{1}{3}$\\*
&&&&&& \\*
\hline
\end{longtable}
\normalsize
\end{figure}
#+end_export

**** Baryons
**** Mesons

#+begin_export latex
\begin{figure}[H]
\centering
\begin{picture}(150, 150)(-100, -100)
\put(-25,42){\line(-3,-5){25}}
\put(-25, 42){\line(1, 0){50}}
\put(25, 42){\line(3,-5){25}}
\put(-25, -42){\line(1,0){50}}
\put(-25, -42){\line(-3, 5){25}}
\put(25, -42){\line(3, 5){25}}
\put(-25, 42){\circle*{3}}
\put(-25, -42){\circle*{3}}
\put(25, 42){\circle*{3}}
\put(25, -42){\circle*{3}}
\put(-50, 0){\circle*{3}}
\put(50, 0){\circle*{3}}
\put(0, 0){\circle*{3}}
\put(-28, 47){$K^{0}$}
\put(-50, 40){$(d \bar{s})$}
\put(28, 47){$K^{+}$}
\put(40, 40){$(u\bar{s})$}
\put(-28, -55){$K^{-}$}
\put(-28, -70){$(s\bar{u})$}
\put(28, -55){$\bar{K}^{0}$}
\put(28, -70){$(s\bar{d})$}
\put(55, 0){$\pi^{+}$}
\put(55, -17){$(u \bar{d})$}
\put(-65, 0){$\pi^{-}$}
\put(-67, -17){$(d \bar{u})$}
\put(0, 10){$\pi^{0}$}
\put(-17, -17){$(d \bar{d} / u \bar{u})$}
\end{picture}
\caption{Mesons}
\end{figure}
#+end_export

*** Leptons

Leptons are /fundamental/ particles: they are indivisible. There are two types of lepton: the /electron/ and the /muon/. There are specific neutrinos for each lepton type. During interactions the muon lepton number and the electron number are conserved. Leptons do not interact due to the strong force.

#+begin_export latex
\begin{figure}[H]
\small
\begin{longtable}{ |C{0.2\textwidth}|C{0.2\textwidth}|C{0.2\textwidth}|C{0.2\textwidth}| }
\hline
&&&\\*
\textbf{Particle} & \textbf{Electron Number} & \textbf{Muon Number} & \textbf{Charge} \\*
&&&\\*
\hline
\endhead
&&&\\*
$e^-$&$+1$&$0$&$-1$\\*
&&&\\*
\hline
&&&\\*
$e^+$&$-1$&$0$&$+1$\\*
&&&\\*
\hline
&&&\\*
$u^-$&$0$&$+1$&$-1$\\*
&&&\\*
\hline
&&&\\*
$u^+$&$0$&$-1$&$+1$\\*
&&&\\*
\hline
&&&\\*
$v_e$&$+1$&$0$&$0$\\*
&&&\\*
\hline
&&&\\*
$\bar{v}_e$&$-1$&$0$&$0$\\*
&&&\\*
\hline
&&&\\*
$v_u$&$0$&$+1$&$0$\\*
&&&\\*
\hline
&&&\\*
$\bar{v}_u$&$0$&$-1$&$0$\\*
&&&\\*
\hline
\end{longtable}
\normalsize
\end{figure}
#+end_export

Muons eventually decay into electrons and neutrinos, which are required to maintain the muon and electron lepton numbers.

\[u^- \rightarrow e^- + \bar{v}_e + v_u\]
\[u^+ \rightarrow e^+ + v_e + \bar{v}_u\]

** Photons & Energy

When charged particles undergo some change in energy, electromagnetic waves are created. These exist in /discrete/ packets called /photons/. The energy of a photon is tied to the frequency of the wave it represents in the form:

\[E = hf\]

*** Annihilation

The energy gained by a particle is linked to its increase in mass via $E = mc^2$. Given that an object at rest has mass, it has a corresponding /rest energy/, equal to $m_0c^2$. This energy is stored permanently as mass, although it is still subject to the laws of conservation of energy.

Where matter meets antimatter, specifically the correct /antiparticle/, rest energy can be released in a process called /annihilation/. The total rest mass of the two particles combined is converted into photon energy. Two photons are always produced to endure that the total difference in momentum is $0$. During annihilation, the total rest mass of the particle/antiparticle pair is $2E_0$ and two photons are produced, so:

\[2E_0 = 2hf_{min}\]

For each photon produced, the minimum energy is therefore equal to:

\[hf_{min} = E_0\]

*** Pair Production

A high energy photon is capable of producing a particle/antiparticle pair. The energy of a photon must be equal to twice the rest mass of the particle in question.

\[hf_{min} = 2E_0\]

* Fields and their Consequences
** Gravitational Fields

Any object with mass creates a /gravitational field/ around itself. Any other mass placed within this field experiences an attractive force and exerts an equal attractive force on the first object.

*** Gravitational Field Strength

If a small test mass is placed inside the gravitational field of a much larger mass, the force of gravitation experienced by both objects will cause a much greater acceleration to the small test mass, according to $F = ma$. The gravitational field strength $g$, is the force per unit mass ($Nkg^{-1}$) experienced by a small test mass positioned in a gravitational field. There is a direct relationship between $g$ and the acceleration $a$ of a small test mass.

\[g = \dfrac{F}{m}\]

\[a = \dfrac{F}{m}\]

*** Radial and Uniform Fields

The direction of the forces surrounding a mass are shown in /field-diagrams/, these represent the path taken by a small test mass in a gravitational field. The density of field lines and their proximity to one another indicate the magnitude of $g$ at that point. The field around a planet or other spherical object is /radial/. Each field line is directed towards the centre of the mass. The density of field lines decreases with distance from the mass, showing that $g$ decreases away from a mass.

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.4 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (0,2)--(0,0);
    \draw[postaction={decorate}] (0,-2)--(0,0);
    \draw[postaction={decorate}] (-2,0)--(0,0);
    \draw[postaction={decorate}] (2,0)--(0,0);
    \draw[postaction={decorate}] (1.41,1.41)--(0,0);
    \draw[postaction={decorate}] (1.41,-1.41)--(0,0);
    \draw[postaction={decorate}] (-1.41,1.41)--(0,0);
    \draw[postaction={decorate}] (-1.41,-1.41)--(0,0);
\end{scope}
\filldraw[fill=blue!40!white, draw=black] (0,0) circle (0.4cm);
\end{tikzpicture}
\caption{A radial graviatational field}
\end{figure}

#+end_export

If the same object is observed much more closely, radial field lines may appear parallel to one another and hence there is no change in the magnitude of $g$ within the selected region of the gravitational field.

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\fill[blue!40!white] (-2,3) rectangle (-1.5, -3);
\begin{scope}[very thick,decoration={ markings, mark=at position 0.55 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[] (-1.5, 3) -- (-1.5, -3);
    \draw[postaction={decorate}]  (1.5,2.5) -- (-1.5,2.5);
    \draw[postaction={decorate}]  (1.5,2.0) -- (-1.5,2.0);
    \draw[postaction={decorate}]  (1.5,1.5) -- (-1.5,1.5);
    \draw[postaction={decorate}]  (1.5,1.0) -- (-1.5,1.0);
    \draw[postaction={decorate}]  (1.5,0.5) -- (-1.5,0.5);
    \draw[postaction={decorate}]  (1.5,0.0) -- (-1.5,0.0);
    \draw[postaction={decorate}]  (1.5,-0.5) -- (-1.5,-0.5);
    \draw[postaction={decorate}]  (1.5,-1.0) -- (-1.5,-1.0);
    \draw[postaction={decorate}]  (1.5,-1.5) -- (-1.5,-1.5);
    \draw[postaction={decorate}]  (1.5,-2.0) -- (-1.5,-2.0);
    \draw[postaction={decorate}]  (1.5,-2.5) -- (-1.5,-2.5);
\end{scope}
\end{tikzpicture}
\caption{A "uniform" graviatational field}
\end{figure}
#+end_export

*** Gravitational Potential

The /gravitational potential/ at a point in a gravitational field is the /gravitational potential energy/ per unit mass of a small test mass. It can also be described as the work done per unit mass to move an object from infinite distance to that point.

- The gravitational field around an object extends to /infinity/. The strength of this field diminishes with distance from the centre of the object.

- Any object within a gravitational field will have /gravitational potential energy/ (the energy of an object due to its position in a gravitational field).

- For any object in a gravitational field, its *GPE* is least when it is close to the centre of the field and larger at greater distances from the centre of the field. *GPE* is $0$ at the infinity position. Consequently, values of *GPE* closer to the centre of the field are negative.

The unit of gravitational potential is the $Jkg^{-1}$ and like *GPE*, values are always negative. *GP* is expressed algebraically like this:

\[V = \dfrac{W}{M}\]

Points in a gravitational field which are the same distance from the centre of the field will share the same value of $V$. These loci of points are called /equipotentials/ and no work is done against the gravitational field when an object moves along an equipotential.


#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.4 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
\end{scope}
\filldraw[fill=blue!40!white, draw=black] (0,0) circle (1cm);
\draw (0,0) circle (2.2cm);
\draw (0,0) circle (3.4cm);
\draw (0,0) circle (5.2cm);
\node[] at (0,1.25) {$-100$};
\node[] at (0,2.45) {$-80$};
\node[] at (0,3.6) {$-60$};
\node[] at (0,5.5) {$-40$};
\node[] at (5,5) {$MJkg^{-1}$};
\end{tikzpicture}
\caption{Equipotentials around a spherical body (not to scale)}
\end{figure}
#+end_export

*** Potential Gradients

The /potential gradient/ at a point in a gravitational field is the change in potentail per metre at that point. As $g$ decreases with distance from a given mass, the change in $V$ per metre at greater distances from the centre of the field decreases. The potential gradient = $\Delta V / \Delta r$, these values are labelled in the figure.

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.4 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
\end{scope}
\filldraw[fill=blue!40!white, draw=black] (0,0) circle (1cm);
\draw (0,0) circle (2.2cm);
\draw (0,0) circle (3.4cm);
\filldraw[black] (1.55, 1.55) circle (0.12cm);
\filldraw[black] (2.4, 2.4) circle (0.12cm);
\draw[-{Latex[length=2mm, width=2mm]}, gray] (1.7, 1.7) -- (2.25, 2.25);
\node[] at (1.25,1.25) {$m$};
\node[] at (2.5,0) {$V$};
\node[] at (4.3,0) {$V+ \Delta V$};
\node[] at (2.4,1.5) {$\Delta r$};
\end{tikzpicture}
\caption{Potential gradient}
\end{figure}
#+end_export

If the test mass $m$ is moved a distance $\Delta r$ away from the planet, its *GPE* will increase as it moves to a point of higher potential. A force must be applied to the object, which is equal and opposite to the force due to gravity, acting through $\Delta r$.

\[\Delta W = F \Delta r\]

\[\Delta V = \dfrac{\Delta W}{m}\]

\[\Delta V = \dfrac{F \Delta r}{m}\]

\[F = \dfrac{m \Delta V}{\Delta r}\]

\[F_{grav} = -F\]

\[F_{grav} = - \dfrac{m \Delta V}{\Delta r}\]

\[g = \dfrac{F_{grav}}{m}\]

\[g = - \dfrac{\Delta V}{\Delta r}\]

This proves that the gravitational field strength is the negative of the potential gradient at any point, therefore it acts in the opposite direction (towards the planet).

*** Law of Gravitation

Newton's law of gravitation describes an attractive force between any two point objects. It is directly proportional to the product of the masses of the two objects and inversely proportional to the square of the separation between the two points.

\[F = \dfrac{Gm_1m_2}{r^2}\]

The constant of proportionality $G$ is called the /universal constant of gravitation/. Its value is $6.67 \times 10^{-11} \text{} Nm^2kg^{-2}$.

*** Planetary Fields

The field of a large spherical body such as a planet is the same as if its mass were concentrated at a single central point. For a large point mass $M$, the force exerted on a small test mass $m$, where $m < M$, at distance $r$ is determined with Newton's law of gravitation.

\[F = \dfrac{GMm}{r^2}\]

The gravitational field strength $g = F / m$ is equal to:

\[g = \dfrac{GM}{r^2}\]

These equations are true if $r > R$, where $R$ is the radius of the planetary body; At or beyond the radius of the planet, the value of $M$ is constant and the proportionality is accurate. The surface gravitational field strength is a special form of the equation:

\[g_s = \dfrac{GM}{R^2}\]

\[GM = R^2g_s \]

\[g = \dfrac{GM}{r^2}\]

\[g = \dfrac{R^2g_s}{r^2}\]

Values of $r$ that are smaller than $R$ indicate positions within the planet itself. At these positions, only the mass located in the hypothetical sphere with radius of the original centre of the planet to the current position $r$. Within the planet, $g$ decreases along with $r$ to 0 at the centre, as the mass at the exact centre is 0.

\[g = \dfrac{GM}{r^2}\]

\[V = \dfrac{4}{3} \pi r^3\]

\[M = \rho V = \dfrac{4}{3} \rho \pi r^3\]

\[g = \dfrac{G \dfrac{4}{3} \rho \pi r^3}{r^2}\]

\[g = \dfrac{4}{3} G \rho \pi r\]

This final form of the equation is only valid when $r < R$. This equation demonstrates a different type of relationship between $g$ and $r$ to the initial equation for $g$. When $g$ is plotted against $r$, the relationship is linear and positive between $0$ and $R$. Beyond $R$, the relationship is one of the form $k/r^2$.

#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=0.8\textwidth,keepaspectratio]{./images/gravitational_field_strength.png}
\caption{Field strength within and beyond R}
\end{figure}
#+end_export

The gravitational potential at distance $r$ from a point mass is given by:

\[V = - \dfrac{GM}{r}\]

Therefore, the energy required to move an object from that point to infinity is:

\[\Delta W = m \Delta V\]

\[\Delta W = \dfrac{GMm}{r} \]

In this example the change in potential is equal to the magnitude of the potential at the point as the potential is defined by the energy require to move a mass from a given point to /infinity/. The work done to move a mass $m$ a small distance $r$ in a gravitational field can also be calculated by measuring the area under a $g/r$ graph.

\[\Delta W = gm \Delta r = F \Delta r  \]

\[ \Delta W = \dfrac{GMm}{r^2} \Delta r \]

If an object of mass $m$ is positioned on the surface of a planet with mass $M$ and radius $R$ the /escape velocity/ is the velocity it must be given to escape the gravitational field of the planet. Scientifically speaking, /escape velocity/ is the speed at which the sum of an object's kinetic energy and its gravitational potential energy is equal to zero. A rocket propelled by its own engines can escape a field without ever reaching escape velocity, as work done by its engines will add kinetic energy. Algebraically:

\[\dfrac{1}{2} m v^2 \ge \Delta W\]

\[\dfrac{1}{2} m v^2 \ge \dfrac{GMm}{r}\]

\[ v_{esc} = \sqrt{\dfrac{2GM}{r}}\]

\[g = \dfrac{GM}{R^2}\]

\[ v_{esc} = \sqrt{2gR}\]


The graph of $V$ against $r$ proves the $1/r$ relationship. At any point the gradient is $\Delta V / \Delta r$, which is equal to $-g$.

#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=0.8\textwidth,keepaspectratio]{./images/gravitational_potential.png}
\caption{Increase in potential with radius}
\end{figure}
#+end_export

*** Satellite Motion

According to /Kepler's Third Law/, the time period of a planet orbiting the sun depends on the mean radius of the orbit,  $T^2 \propto r^3$. The gravitational force of attraction between a body and a satellite is the centripetal force acting on the satellite. Therefore, the gravitational field strength is equivalent to centripetal acceleration.

\[\dfrac{v^2}{r} = \dfrac{GM}{r^2}\]

\[v^2 = \dfrac{GM}{r}\]

\[\left (\dfrac{2 \pi r}{T} \right )^2 = \dfrac{GM}{r}\]

\[\dfrac{4 \pi^2 r^2}{T^2} = \dfrac{GM}{r}\]

\[\dfrac{r^3}{T^2} = \dfrac{GM}{4 \pi^2 }\]

Seeing as *RHS* is a constant, the value of $r^3/T^2$ is also constant for all planets.

The *KE* and *PE* of an orbiting satelite are as follows:

\[E_k = \dfrac{1}{2} m v^2 = \dfrac{1}{2} m \dfrac{GM}{r} = \dfrac{GMm}{2r}\]

\[E_p = mV = -\dfrac{GMm}{r}\]

\[ E = E_k + E_p\]

\[E = \dfrac{GMm}{2r} -\dfrac{GMm}{r} \]

\[E =-\dfrac{GMm}{2r} \]

** Electric Fields

Like masses, charges produce a force-field around themselves. Any two objects with like-charges create equal and opposite forces on one another. If one of these charges is a small test charge in the field of a much larger charge it will follow a path away from the body with the larger charge, along a field line.

Unlike gravitational fields, electric fields may be attractive or repulsive. Electric fields are defined in terms of positive charge and field lines indicate the direction a small positive test charge might take.

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.6 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (0,0)--(0,2);
    \draw[postaction={decorate}] (0,0)--(0,-2);
    \draw[postaction={decorate}] (0,0)--(-2,0);
    \draw[postaction={decorate}] (0,0)--(2,0);
    \draw[postaction={decorate}] (0,0) -- (1.41,1.41);
    \draw[postaction={decorate}] (0,0) -- (1.41,-1.41);
    \draw[postaction={decorate}] (0,0) -- (-1.41,1.41);
    \draw[postaction={decorate}] (0,0) -- (-1.41,-1.41);
\end{scope}
\filldraw[red] (0,0) circle (0.2cm);
\end{tikzpicture}
\caption{The field around a positive charge}
\end{figure}
#+end_export

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.5 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (0,2)--(0,0);
    \draw[postaction={decorate}] (0,-2)--(0,0);
    \draw[postaction={decorate}] (-2,0)--(0,0);
    \draw[postaction={decorate}] (2,0)--(0,0);
    \draw[postaction={decorate}] (1.41,1.41)--(0,0);
    \draw[postaction={decorate}] (1.41,-1.41)--(0,0);
    \draw[postaction={decorate}] (-1.41,1.41)--(0,0);
    \draw[postaction={decorate}] (-1.41,-1.41)--(0,0);
\end{scope}
\filldraw[blue] (0,0) circle (0.2cm);
\end{tikzpicture}
\caption{The field around a negative charge}
\end{figure}
#+end_export


#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\filldraw[red] (-2, 0) circle (0.1cm);
\filldraw[blue] (2, 0) circle (0.1cm);
\begin{scope}[very thick,decoration={ markings, mark=at position 0.6 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (-2,0)--(-4,0);
    \draw[postaction={decorate}] (-2,0)--(-2,2);
    \draw[postaction={decorate}] (-2,0)--(-2,-2);
    \draw[postaction={decorate}] (-2,0)--(-3.41,1.41);
    \draw[postaction={decorate}] (-2,0)--(-3.41,-1.41);
\end{scope}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.5 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (4,0) -- (2,0);
    \draw[postaction={decorate}] (2,2) -- (2,0);
    \draw[postaction={decorate}] (2,-2) -- (2,0);
    \draw[postaction={decorate}] (3.41,1.41) -- (2,0);
    \draw[postaction={decorate}] (3.41,-1.41) -- (2,0);
\end{scope}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.53
with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (-2,0) -- (2,0);
    \draw[postaction={decorate}] (-2,0) .. controls (-0.59, 1.41) and (0.59, 1.41) .. (2,0);
    \draw[postaction={decorate}] (-2,0) .. controls (-0.59, -1.41) and (0.59, -1.41) .. (2,0);
\end{scope}
\filldraw[red] (-2, 0) circle (0.2cm);
\filldraw[blue] (2, 0) circle (0.2cm);
\end{tikzpicture}
\caption{The field around two opposite charges}
\end{figure}
#+end_export

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.6 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (-2,0)--(-4,0);
    \draw[postaction={decorate}] (-2,0)--(-2,2);
    \draw[postaction={decorate}] (-2,0)--(-2,-2);
    \draw[postaction={decorate}] (-2,0)--(-3.41,1.41);
    \draw[postaction={decorate}] (-2,0)--(-3.41,-1.41);
\end{scope}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.6 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (2,0)--(4,0);
    \draw[postaction={decorate}] (2,0)--(2,2);
    \draw[postaction={decorate}] (2,0)--(2,-2);
    \draw[postaction={decorate}] (2,0)--(3.41,1.41);
    \draw[postaction={decorate}] (2,0)--(3.41,-1.41);
\end{scope}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.53
with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[postaction={decorate}] (-2,0) .. controls (-1, 1) .. (-0.8, 2);
    \draw[postaction={decorate}] (-2,0) .. controls (-1, -1) .. (-0.8, -2);
    \draw[postaction={decorate}] (2,0) .. controls (1, 1) .. (0.8, 2);
    \draw[postaction={decorate}] (2,0) .. controls (1, -1) .. (0.8, -2);
    \draw[gray, dashed] (0,2) -- (0, -2);
\end{scope}
\filldraw[red] (-2, 0) circle (0.2cm);
\filldraw[red] (2, 0) circle (0.2cm);
\end{tikzpicture}
\caption{The field around two like charges}
\end{figure}
#+end_export

*** Electric Field Strength

The electric field strength $E$ at a point in an electric field is the force per unit charge on a positive test charge placed at that point.

\[E = \dfrac{F}{Q}\]

*** Uniform Electric Fields

The field lines between two parallel oppositely charged plates are parallel to one another and perpendicular to the plates. The field lines are directed from the positive to negative plate. The field lines are evenly spaced throughout the field, therefore $E$ is the same at every point in the field:

\[E = \dfrac{V}{d}\]

The electric field strength is given by the potential difference over the separation of the two plates.

\[F = QE\]

\[W = Fd = QEd\]

\[W = Fd = QEd\]

\[V = \dfrac{W}{Q} = \dfrac{QEd}{Q}\]

\[V = Ed\]

\[E = \frac{V}{d}\]

#+begin_export latex
\begin{figure}[H]
\centering
\begin{tikzpicture}
\begin{scope}[very thick,decoration={ markings, mark=at position 0.55 with {\arrow[]{Latex[length=2mm, width=2mm]}}}]
    \draw[] (-1.5, 3) -- (-1.5, -3);
    \draw[] (1.5, 3) -- (1.5, -3);
    \draw[postaction={decorate}, gray] (-1.5,2.5) -- (1.5,2.5);
    \draw[postaction={decorate}, gray] (-1.5,2.0) -- (1.5,2.0);
    \draw[postaction={decorate}, gray] (-1.5,1.5) -- (1.5,1.5);
    \draw[postaction={decorate}, gray] (-1.5,1.0) -- (1.5,1.0);
    \draw[postaction={decorate}, gray] (-1.5,0.5) -- (1.5,0.5);
    \draw[postaction={decorate}, gray] (-1.5,0.0) -- (1.5,0.0);
    \draw[postaction={decorate}, gray] (-1.5,-0.5) -- (1.5,-0.5);
    \draw[postaction={decorate}, gray] (-1.5,-1.0) -- (1.5,-1.0);
    \draw[postaction={decorate}, gray] (-1.5,-1.5) -- (1.5,-1.5);
    \draw[postaction={decorate}, gray] (-1.5,-2.0) -- (1.5,-2.0);
    \draw[postaction={decorate}, gray] (-1.5,-2.5) -- (1.5,-2.5);
\end{scope}
\node[] at (-1.5,-3.5) {$+$};
\node[] at (1.5,-3.5) {$-$};
\end{tikzpicture}
\caption{A uniform electric field}
\end{figure}
#+end_export

*** Electric Potential

The electric potential at a point in an electric field is the energy per positive unit charge required to move it from infinity to that point. The potential gradient at a point in an electrical field is the change in potential per unit change of distance in an a given direction. The electric field strength is equal to the negative potential gradient:

\[E = - \dfrac{\Delta V}{ \Delta x}\]

*** Coulomb's Law

Coulomb's law links the magnitude of force existing between two point charges with the distance between them. This is an inverse square relationship.

\[F = \dfrac{kQ_1Q_2}{r^2}\]

\[k = \dfrac{1}{4 \pi \epsilon_0}\]

\[\epsilon_0 = 8.85 \times 10^-12 \]

For a small positive test charge q in an electric field around charge $+Q$:


\[F = \dfrac{Qq}{4 \pi \epsilon_0r^2}\]

\[E = \dfrac{F}{q}\]

\[E = \dfrac{Q}{4 \pi \epsilon_0r^2}\]

If $Q$ was a negative charge, the value of $E$ would also be negative, indicating an attractive force on the positive test charge $q$.

The electric potential at distance $r$ from $Q$ is:

\[V = \dfrac{Q}{4 \pi \epsilon_0r}\]

The potential energy is:

\[E_p = \dfrac{Qq}{4 \pi \epsilon_0r}\]

** Capacitors

A capacitor is a component designed to store charge. Two metal plates positioned near one another form a capacitor. When connected across the terminals of a battery, electrons are forces from the negative terminal of the battery onto one of the capacitor plates. A similar number of electrons leave the opposite plate of the capacitor. Each plate gains an equal and opposite charge.

*** Charge Stored in a Capacitor

If the total charge stored on a capacitor is $Q$, the charge on each plate is equal to $\pm Q$. If a capacitor is charged at constant current, the /capacitance/ is said to be the charge stored per volt.

\[C = \dfrac{Q}{V}\]

*** Energy Stored in a Capacitor

The energy stored in a capacitor is the area under a $V/Q$ graph.

\[E = \dfrac{1}{2} QV\]

\[E = \dfrac{1}{2} (CV)V^2\]

\[E = \dfrac{1}{2} CV^2\]

* Nuclear Physics
** Radiation
** Inverse Square Law

The intensity $I$ of $\gamma$ radiation is the energy transferred per second per unit area. Assuming a point source emits $n$ $\gamma$ photons per second and each photon has the energy $hf$, the total energy emitted by the source per second is $nhf$. These photons are free to leave the source in any direction, so at distance $r$ from the source all the photons will pass through an area equal to the /S.A./ of a sphere with radius $r$. This equation represents the intensity of radiation from a point source at distance $r$:

\[I = \dfrac{nhf}{4 \pi r^2}\]

** Hazards of Radiation

Ionising radiation is damaging to living cells. It may cause cells to die, mutate or grow uncontrollably. The consequences may be felt by the affected individual, which is described as /somatic effects/, or passed onto future generations /genetically/.

To best mitigate the risks of radiation, sources should be kept in /lead-lined/ containers to reduce any $\gamma$ emission from the source to background level. These sources may be kept in a secure, locked-away location and exposure / use of the source should be recorded.

During use, solid sources should be handled with handling tools, to keep the source at a distance from the body. This reduces the intensity of $\gamma$ radiation incident on the handler and would ideally put their body beyond the range of $\alpha$ or $\beta$ particles. Liquid, gaseous and powdered sources should be kept in sealed containers, so they are not accidentally inhaled, ingested or split.

** Radioactive Decay

If a radioactive isotope of element $X$ undergoes $\alpha$ or $\beta$ emission, it is no longer a nucleus of the same element, due to the change in proton number. If this nucleus was one of many in a sample of a particular isotope, the number of nuclei of this isotope will decrease as individual nuclei decay. The same relationship is true of the mass of the original isotope; the mass will decrease as nuclei decay. There are three important quantities surrounding radioactive decay:

- The /half-life/ $T_{1/2}$ of a radioactive isotope is the time take for the mass (or any other specific property) to decrease to half the initial value.

- The /activity/ $A$ of a radioactive isotope is the number of nuclei disintegrating per second, corresponds to the rate of changes of nuclei of the initial isotope. The unit of activity is the /Becquerel/ (Bq), where 1Bq is one disintegration per second.

- The /decay constant/ $\lambda$ is the probability of an individual nucleus decaying per unit time (usually one second).

The decay of a single nucleus is impossible to predict. Every nucleus of an isotope in a sample has an equal probability of decaying in a given interval. For a large sample of a radioactive isotope $X$, the number of nuclei which disintegrate $\Delta N$ in a given time period $\Delta t$ is related to the initial number of nuclei $N_0$, via the decay constant.

*** Decay Constant

The probability of a single decay is the fraction of the initial number of nuclei of $X$ which decay per second. This is called the /decay constant/, and is represented with the symbol $\lambda$. If reference is made to /decay/ or its decreasing nature, there is no need to include a minus sign.

\[\lambda = \dfrac{\Delta N}{N_0}/\Delta t\]

The change in number of nuclei for a combination of the given factors can be obtained by rearranging the equation above. Note the presence of the minus sign here indicating decrease.

\[ \Delta N = - \lambda N_0 \Delta t\]

*** Activity

The activity of the isotope is the number of nuclei which disintegrate per second and it is proportional to the value of $N_0$. An expression for $A$ can be obtained as follows:

\[ \dfrac{\Delta N}{\Delta t} = - \lambda N_0\]

\[ A = - \lambda N_0\]

Therefore the activity of $N$ nuclei of a particular isotope can also be written simply:

\[ A = \lambda N\]

*** Decay Curves

As the activity, or rate of change of nuclei of $X$, is proportional to the current number of nuclei $N$ of $X$, the relationship between $t$ and $N$ is one of exponential decay. The number of nuclei remaining after a particular time period is proportional to $N_0$.

\[N = N_0 e^{- \lambda t}\]

#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=0.8\textwidth,keepaspectratio]{./images/c-14_decay.png}
\caption{Decay curve of C-14}
\end{figure}
#+end_export

Both activity and mass are directly related to the number of nuclei.

\[m = m_0 e^{- \lambda t}\]
\[A = A_0 e^{- \lambda t}\]

*** Half-life

Half-life can be linked to the decay constant. When $t= T_{1/2}$, the number of nuclei remaining is $N = 0.5N_0$. With these equations, substitutions can be made:

\[0.5N_0 = N_0 e^{-\lambda T_{1/2}}\]

\[0.5 = e^{-\lambda T_{1/2}}\]

\[\ln (0.5) = -\lambda T_{1/2}\]

\[-\ln (0.5) = \lambda T_{1/2}\]

\[\ln (0.5^{-1}) = \lambda T_{1/2}\]

\[\ln (2) = \lambda T_{1/2}\]

\[T_{1/2} = \dfrac{\ln(2)}{\lambda}\]

#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=0.8\textwidth,keepaspectratio]{./images/c-14_t_half.png}
\caption{Various half-lives of C-14}
\end{figure}
#+end_export

** Nuclear Radius

The radius of a nucleus is proportional to the cube root of the nucleon number and the constant $r_0$, which is equal to $1.05fm$.

\[R = r_0 A^{1/3}\]

\[V = \dfrac{4}{3} \pi R^3 = \dfrac{4}{3} \pi (r_0 A^{1/3})^3 = \dfrac{4}{3} \pi {r_0}^3 A\]

Seeing as the mass of a nucleus is equal to $Au$, where $u$ is the atomic mass unit, the density of any nucleus is constant.

\[\rho = \dfrac{Au}{4/3 \text{ } \pi {r_0}^3 A} = \dfrac{1u}{4/3 \text{ } \pi {r_0}^3}\]

When evaluated, the density of a nucleus of any element is $3.4 \times 10^{17}$.

** Energy and Mass

The equation $E = mc^2$ links the energy of an object to the change of its mass and the speed of light in free space. Consequently, the mass of any object changes as it gains or loses energy. This is only significant on the nuclear/sub-nuclear scale. The energy released during a reaction is $Q = \Delta mc^2$, where $\Delta m$ is the difference in mass before and after the interaction.

** Binding Energy

The binding energy of a nucleus is the work done to separate all of the protons and neutrons from the nucleus. When a nucleus is formed from individual nucleons, energy is released amounting to the binding energy of the nucleus. Due to this release of energy the mass of the nucleus is less than the sum of the masses of constituent nucleons.

The mass defect $\Delta m$ of a nucleus is the difference between the sum of the masses of separated nucleons and the mass of the whole nucleus. The mass defect for a $^A_ZX$ nucleus can be calculated with this equation.

\[\Delta m =  Zm_p + (A-Z)m_n - M_{\text{NUC}} \]

Where $m_p$ and $m_n$ are the masses of a proton and a neutron respectively and $M_{\text{NUC}}$ is the mass of the whole nucleus. The binding energy is equal to: $Q = \Delta mc^2$. The values of $m_p$ and $m_n$ are often quoted in terms of $u$, the atomic mass unit.

- $1u = 1.661 \times 10^{-27}kg= 931.3MeV$
- $m_p = 1.00728u$
- $m_n = 1.00867u$

** Quantum Tunnelling

Two protons and two neutrons in a nucleus may bind together to as a cluster, which may be ejected from the nucleus as an $\alpha$ particle. The $\alpha$ particle is given a large amount of energy during its formation.

** Nuclear Stability

Each nucleus has a binding energy and a specific binding energy per nucleon. This is the binding energy divided by the nucleon number of the nucleus. This value is indicative of the stability of the nucleus. More stable nuclei have a larger binding energy per nucleon. The maximum value is approximately $8.7Mev$, occurring in the region $50 \le A \le 60$.

#+begin_export latex
\begin{figure}[H]
\centering
\includegraphics[width=0.8\textwidth,keepaspectratio]{./images/nuclear_stability.png}
\caption{A graph of nuclear stability}
\end{figure}
#+end_export

The orange line in the figure indicates the position of Fe-56, a very stable isotope of Iron. Energy is released in nuclear events under certain conditions:

- Fusion of nuclei to the left of the division. When heavier nuclei are formed energy is released due to the greater binding energy per nucleon of the resulting nuclei.

- Fission of nuclei to the right of the division. When multiple, lighter daughter nuclei are formed energy is released due to the greater binding energy per nucleon of the resulting nuclei.
